excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dawill12345.github.io
name: Geekly
description: On this site, it's just me blogin about stuff. Usually it's about computers, filmmaking, and other stuff. 
author: William Redenbagh
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 